POST http://localhost:5000/createTask
Content-Type: application/json

{
    "task": "weile",
    "day": "rawr"
}

###

DELETE http://localhost:5000/deleteTask/63572ca11b085d417c5e8f86
Content-Type: application/json
